name: Performance and Load Testing

on:
  workflow_dispatch:
    inputs:
      concurrent_users:
        description: 'Number of concurrent users'
        required: false
        default: '10'
        type: string
  release:
    types: [published]

env:
  PYTHON_VERSION: '3.11'

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust

    - name: Create Load Test File
      run: |
        cat << 'LOCUST_EOF' > locustfile.py
        from locust import HttpUser, task, between
        import random

        class GitHubEventsUser(HttpUser):
            wait_time = between(1, 3)

            @task(5)
            def check_health(self):
                self.client.get("/health", name="/health")

            @task(3)
            def get_event_counts(self):
                minutes = random.choice([10, 30, 60])
                self.client.get(f"/metrics/event-counts?offset_minutes={minutes}", 
                               name="/metrics/event-counts")

            @task(2)
            def get_trending(self):
                self.client.get("/metrics/trending?hours=24&limit=10",
                               name="/metrics/trending")
        LOCUST_EOF

    - name: Start GitHub Events Monitor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m github_events_monitor.api &
        sleep 30
        curl -f http://localhost:8000/health

    - name: Run Load Test
      env:
        USERS: ${{ github.event.inputs.concurrent_users || '10' }}
      run: |
        locust -f locustfile.py           --host=http://localhost:8000           --users=$USERS           --spawn-rate=2           --run-time=120s           --html=load_test_report.html

    - name: Upload Load Test Results
      uses: actions/upload-artifact@v3
      with:
        name: load-test-results
        path: load_test_report.html
