name: Documentation Generation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start API Server
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m github_events_monitor.api &
        sleep 30

    - name: Generate API Documentation
      run: |
        curl http://localhost:8000/openapi.json > docs/openapi.json

    - name: Create Usage Examples
      run: |
        mkdir -p docs/examples
        cat << 'EXAMPLE_EOF' > docs/examples/api_usage.md
        # API Usage Examples

        ## Health Check
        ```bash
        curl http://localhost:8000/health
        ```

        ## Get Event Counts
        ```bash
        curl "http://localhost:8000/metrics/event-counts?offset_minutes=60"
        ```

        ## Repository Activity
        ```bash
        curl "http://localhost:8000/metrics/repository-activity?repo=microsoft/vscode&hours=24"
        ```

        ## Trending Repositories
        ```bash
        curl "http://localhost:8000/metrics/trending?hours=24&limit=10"
        ```

        ## Interactive API Documentation
        Visit: http://localhost:8000/docs
        EXAMPLE_EOF

    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: |
          docs/

  deploy-docs:
    runs-on: ubuntu-latest
    needs: generate-docs
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download documentation
      uses: actions/download-artifact@v3
      with:
        name: documentation
        path: ./docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/
        destination_dir: docs
