name: Pages on issue request

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write
  pages: write
  id-token: write

jobs:
  parse-and-dispatch:
    if: contains(github.event.issue.labels.*.name, 'dashboard-request')
    runs-on: ubuntu-latest
    steps:
      - name: Extract repos from issue body
        id: extract
        run: |
          body='${{ github.event.issue.body }}'
          echo "Body: $body" | sed -E 's/.{0,200}/&\n/g'
          # Expect a line like: repos=owner/repo1,owner/repo2
          repos=$(printf "%s" "$body" | grep -i '^repos=' | head -n1 | cut -d'=' -f2- | tr -d '\r' | xargs)
          echo "repos=$repos"
          echo "repos=$repos" >> $GITHUB_OUTPUT

      - name: Comment on issue if missing repos
        if: steps.extract.outputs.repos == ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Please include a line like `repos=owner/repo1,owner/repo2` in the issue body.'
            })

      - name: Dispatch CI with repos
        if: steps.extract.outputs.repos != ''
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI and Pages
          inputs: |
            {"repositories": "${{ steps.extract.outputs.repos }}"}

      - name: Acknowledge request
        if: steps.extract.outputs.repos != ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Triggered dashboard build for repos: ${process.env.repos}`
            })

