name: Build and Publish Dashboard to Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare DB (create if missing)
        run: |
          mkdir -p database
          if [ ! -f database/events.db ]; then
            sqlite3 database/events.db < database/schema.sql
          fi

      - name: Collect events (single cycle)
        env:
          GITHUB_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOKEN }}
          DB_PATH: database/events.db
          RUN_ONCE: '1'
        run: |
          python service/github_monitor.py --once || true

      - name: Export dashboard artifacts
        env:
          DB_PATH: database/events.db
          TARGET_REPOSITORIES: ${{ vars.TARGET_REPOSITORIES }}
          REPO_SLUG: ${{ github.repository }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          python service/data_exporter.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

