name: Update GitHub Events Database (scheduled)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-db:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t github-events-monitor .

      - name: Initialize and update DB via Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_PATH: github_events.db
        run: |
          docker run --rm \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e DATABASE_PATH=/app/data/github_events.db \
            -v $(pwd)/github_events.db:/app/data/github_events.db \
            github-events-monitor \
            python -c "
          import asyncio
          from src.github_events_monitor.event_collector import GitHubEventsCollector
          async def main():
              collector = GitHubEventsCollector('/app/data/github_events.db', '${{ secrets.GITHUB_TOKEN }}')
              await collector.initialize_database()
              n = await collector.collect_and_store(limit=200)
              print(f'Collected {n} events')
          asyncio.run(main())
          "

      - name: Upload DB artifact
        uses: actions/upload-artifact@v4
        with:
          name: github_events_db
          path: github_events.db


